[profile.default]
src = "."
out = "out"
libs = ["lib"]
solc = "0.8.20"
optimizer = true
optimizer_runs = 200

[profile.default.fuzz]
runs = 256

[rpc_endpoints]
mainnet = "${MAINNET_RPC_URL}"
base = "https://mainnet.base.org"
base_sepolia = "https://sepolia.base.org"
arbitrum = "https://arb1.arbitrum.io/rpc"
arbitrum_sepolia = "https://sepolia-rollup.arbitrum.io/rpc"

[etherscan]
mainnet = { key = "${ETHERSCAN_API_KEY}" }
base = { key = "${BASESCAN_API_KEY}" }
arbitrum = { key = "${ARBISCAN_API_KEY}" }
